services:
  db: 
    profiles: ['dev', 'prod']
    image: postgres:17
    container_name: ${DOCKER_PACKAGE_NAME}_db
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${DOCKER_PACKAGE_NAME}_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5331:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nest-init_network


volumes:
  db_data:

networks:
  nest-init_network:
    driver: bridge

    